version: '3s'

services:
   fastapi-app:
    build: .
    image: fastapi-app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:24032001@db:5432/fastapi-course

   db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=24032001
      - POSTGRES_DB=fastapi-course
volumes:
  postgres_data: